#!/usr/bin/perl
use JSON::PP;

sub account_select {
    my ($accs) = @_;

    my @acc_names = map {
        $_->{name}
    } $accs->@*;

    for (my $i = 0; $i < scalar @acc_names; $i++) {
        printf "%2d %s\n", $i, $acc_names[$i];
    }
    print "Choose wisely: ";
    my $selection = <STDIN>;
    @acc_names[int($selection)];
}

my $output = `az account list`;
my $accs = decode_json($output);
my $acc = account_select($accs);

print `az account set --subscription $acc`;
print `az account show`;
